# -*- coding: utf-8 -*-
"""spatic assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oVVwy4LdPzxuNRhbh8IljfTOSqbVx2c0
"""

import pandas as pd

df=pd.read_excel('/content/assignment_data.xlsx')
df.head()

df=df.rename(columns = {'latitude':'lat','longitude':'lon'})
# To make sure that there are no null values and All are either integers/ Float values 
df.info() 
print('\n XXXXXXXXXXXXXXXXXXXXXXX\n')

from geopy import distance

aAluQtPTMJDSlJ=(13.06119977,77.52655049)
aAluQtPTnMJDSlJ=(13.06219321,77.52658776)

straight_line_distance = distance.great_circle(aAluQtPTMJDSlJ, aAluQtPTnMJDSlJ)
ellipsoid_distance = distance.geodesic(aAluQtPTMJDSlJ, aAluQtPTnMJDSlJ, ellipsoid='WGS-84')

print(straight_line_distance, ellipsoid_distance)

aAluQtPTMJDSlJ=(13.06119977,77.52655049)
aAluQtPTnMJDSlJ=(13.06219321,77.52658776)

straight_line_distance = distance.great_circle(aAluQtPTMJDSlJ, aAluQtPTnMJDSlJ)
ellipsoid_distance = distance.geodesic(aAluQtPTMJDSlJ, aAluQtPTnMJDSlJ, ellipsoid='WGS-84')

print(straight_line_distance, ellipsoid_distance)